framework:
    secret: '%env(APP_SECRET)%'
    default_locale: en
    session:
        handler_id: ~
    php_errors:
        log: true
        throw: true

    cache:
        prefix_seed: schoenholz/pml
