services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    App\:
        resource: '../../*'
        exclude: '../../{Entity,Exception,FilterQuery/Fragment,Migrations,Resources,Tests,Kernel.php}'
