services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    App\:
        resource: '../../*'
        exclude: '../../{Entity,Migrations,Resources,Kernel.php}'
